name: Build and publish LaTeX document

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Configure Git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          root_file: csharp-lecture-notes.tex
          
      - name: Move pdf to root
        run: |
          pwd
          mv src/csharp-lecture-notes.pdf ..
          ls
          

      - name: Commit and Push new file
        run: |
          pwd
          ls
          git add ../csharp-lecture-notes.pdf
          git commit -m "Add PDF file"
          git push
